// header file with necessary components to render clusters
#ifndef CLUSTERS_H
#define CLUSTERS_H

// opengl rendering

// for assimp model loading
#include <assimp/scene.h>
#include <assimp/Importer.hpp>
#include <assimp/postprocess.h>

#include "paper_loader.h"
#include "opengl/shader.h"
#include <glad/glad.h>

// namespace for rendering clusters
namespace Clusters
{
    // ----- Cluster Models ----- //
    struct Vertex
    {
        glm::vec3 position;
        glm::vec3 normal;
    };

    class ClusterMesh
    {
    public:
        ClusterMesh(const std::vector<Vertex>& vertices, const std::vector<unsigned int>& indices);

        void free() const;

        void render(const Shader& shader) const;

    private:
        unsigned int VAO{}, VBO{}, EBO{};

        std::vector<Vertex> m_vertices;
        std::vector<unsigned int> m_indices;

        void setupMesh();
    };;

    class ClusterModel
    {
    public:
        explicit ClusterModel(const std::string& path);

        void free();

        void render(const Shader& shader);

    private:
        std::string m_path;
        std::vector<ClusterMesh> m_meshes{};
        std::string m_directory{};

        void loadModel(const std::string& path);
        void processNode(aiNode* node, const aiScene* scene);

        static ClusterMesh processMesh(const aiMesh* mesh);
    };

    // used to generate convex hull (and export to wavefront)
    struct ConvexHull
    {
        int numVertices{};
        int* faceIndices{nullptr};
        int numFaces{};
    };

    struct ClusterData
    {
        ClusterModel* model{nullptr};
        glm::vec3 position{};
    };

    // loads convex hull for clusters and generates EBO, VBO & VAO
    class ClusterRenderer
    {
    public:
        ClusterRenderer();
        ~ClusterRenderer();

        // generates convex hulls for clusters and saves to wavefront .obj in data/cluster_models
        int generateClusters(const std::vector<std::map<int, Cluster>>& clusters, float scale);

        // load convex hulls for clusters from wavefront .obj files in data/cluster_models (models generated by ClusterRenderer::generateClusters)
        void loadClusters(const std::vector<std::map<int, Cluster>>& clusters);
        // not const because std::map[] isn't const
        ClusterData* getClusterData(int depth, int idx);

        void free();

        // same here
        void renderCluster(const Shader& shader, const glm::mat4& projection, const glm::mat4& view, const glm::vec3& color, int depth, int idx);
        void renderClusterLevel(const Shader& shader, const glm::mat4& projection, const glm::mat4& view, const glm::vec3& color, int depth);

    private:
        // flag to know if we need to free or not
        bool m_loaded{false};
        // contains cluster data for rendering
        std::vector<std::map<int, ClusterData>> m_clusters{};
    };

};

#endif